# Generated by Django 6.0.7 on 2026-08-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفئة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الفئة (مثل: drinks, sweets, fast_food)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='السعر')),
                ('calories', models.IntegerField(verbose_name='السعرات الحرارية')),
                ('details', models.TextField(verbose_name='الوصف التفصيلي')),
                ('ingredients', models.TextField(help_text='أدخل المكونات مفصولة بفواصل (مثال: قهوة, حليب, سكر)', verbose_name='المكونات')),
                ('in_stock', models.BooleanField(default=True, verbose_name='متوفر بالمخزون')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='الفئة')),
            ],
        ),
    ]
